### ISSUE TITLE
About section disappearing on scroll

### ISSUE THREAD

**Issue by azatecas** [agyin3/react-portfolio#35]
While scrolling through the portfolio, i noticed the about section Text disappears way too early while scrolling making it hard to read you about section. I would recommend modifying the event handler to delay removing the Bio text
![Screenshot from 2020-09-25 03-21-46](https://user-images.githubusercontent.com/29685279/94238671-b3259180-fede-11ea-93a6-bfd2f3f577b6.png)

**Comment by agyin3** [comment]
@azatecas Thanks for pointing that out...will look at the timing of the animation and update
